### ISSUE TITLE
"invalid" on vote map screen

### ISSUE THREAD

**Issue by tobi-polar** [DoktorSAS/mapvote#4]
set mv_gametypes "dom;dom.cfg hq;hq.cfg dem;dem.cfg" is what my current dvar looks like but on the vote menu in the gamemode text area it just says invalid

**Comment by DoktorSAS** [comment]
This issue has been addressed by other users.

Seems that the dvar don't work if set from the cfg and must be set in  gsc and seems that the last gametype don't get selected. Soon will be pushed an update to fix the issue.
