### ISSUE TITLE
Error on Compiling

### ISSUE THREAD

**Issue by Zariaa27** [DoktorSAS/mapvote#6]
Hey!
The error below appears when compiling this script, any help would be appreciated.

No code in the GSC file was changed.

[ERROR]:compiler:./mapvote.gsc:1:1: bad token: '∩' at ./mapvote.gsc

**Comment by DoktorSAS** [comment]
For the plutonium client is not required to compile the code. 
That is a syntac error. Check the code again and confirm that you did not type anything without knowing.

Let me know
